### ISSUE TITLE
16.1 falsche widerstandsnahmen (formel <-> bild)

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#12]
R2 im bild ist hier (bei beiden bildern) RK in den formeln. entweder bild auf RK ändern oder formeln auf R2 (letzteres ist denke sinnvoller)

![image](https://user-images.githubusercontent.com/19669567/131395269-641937e9-9f7e-429e-b5eb-0c4f39cc5c94.png)

eventuell wäre hier noch eine notiz praktisch, dass man die formel "einfluss der endlichen verstärkung" hier für b braucht
![image](https://user-images.githubusercontent.com/19669567/131395463-f0b0dd96-3cc2-48b2-a373-d0a7f3ba9253.png)
wobei... notizen in der FS sind ja verboten, also wohl eher nicht

**Comment by jemand771** [comment]
ich hoff mal, das hab ich nicht schonmal reported - ich hab gerade keine soo neue version ^^

**Comment by TheColin21** [comment]
fixed. Die Notiz würde ich schweren Herzens lassen, da wahrscheinlich verboten. eher an die aufgabe schreiben, dass die formel nötig ist
