### ISSUE TITLE
alternative formel für subtrahierverstärker

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#13]
FS aktuell:
![image](https://user-images.githubusercontent.com/19669567/131555516-47056c0c-20a8-4b40-866d-e7807000969a.png)
Aus Reinhold-Skript:
![image](https://user-images.githubusercontent.com/19669567/131555546-5a73479e-72fd-4e41-98a9-a7f5744a3573.png)

es geht um R3 in der FS bzw. R7 im skript. konkret würde ich in der FS dazuschreiben, dass der faktor `\frac{R_3}{R2+R_3}` wegfällt (=1 ist), wenn R3 nicht mit dabei ist. "nicht dabei" interrpetiere ich hier nicht als leerlauf, sondern als kurzschluss auf masse (R3=0 ohm)
siehe `2021-03-04_09-52-45_cut-0.05-1-999999.mkv` ab ca. 29:00. am besten nochmal gucken, dass ich das nicht falsch versteh

**Comment by jemand771** [comment]
mathematisch ist die aussage mit dem R3=0 bisschen müll. weil daraus würde ja dann 0/(0+irgendwas) werden, d.h. faktor 0.
wenn man sagt dass das für den fall R3=unendlich gilt, hätte man unendlich/(unendlich+bisschen) = 1. so rum

also: der "optionale teil" fält weg wenn R3 gar nicht da ist und da **keine** verbindung irgendwohin ist (nicht auf masse kurzgeschlossen). das muss man dann auch nicht unbedingt extra mit hinschreiben, weil man ja von selbst drauf kommt (R3 nicht da -> R3=unendlich, einfach weiter rechnen, dann kommt da wie gesagt 1 als faktor raus)

wollen wir das trotzdem übernehmen? ^^

**Comment by TheColin21** [comment]
ich hätte wahrscheinlich -Ua so umgebaut, wie Ua2 jetzt schon ist. also den R3 Bruch ans Ende und underbrace drunter "falls R3 vorhanden"

**Comment by TheColin21** [comment]
![grafik](https://user-images.githubusercontent.com/24256864/131618161-fcc2205b-6b41-4a6b-88c9-c45dddfbc972.png)
sähe so aus. Ich hab da mal #15 erstellt, sag mal was zu :D

**Comment by jemand771** [comment]
seh gerade, dass in der aktuellen version schon wesentlich mehr in der FS drin steht :D
passt, closed in #15
