### ISSUE TITLE
Zener Diode in Schaltung falsche Richtung

### ISSUE THREAD

**Issue by TheColin21** [TheColin21/Formelsammlung-EB-Latex#16]
![grafik](https://user-images.githubusercontent.com/24256864/131812089-47800e89-5ecc-4c77-8d21-efa0f0ce1f84.png)

Z-Diode wird immer in Sperrrichtung betrieben

**Comment by jemand771** [comment]
@TheColin21 zeig mal das originale bild :D wo stamd/steht das?

**Comment by DSczyrba** [comment]
Uff, ob Willy da Bock hat xd

**Comment by jemand771** [comment]
raus hier @DSczybra

**Comment by DSczyrba** [comment]
manmo :(

**Comment by jemand771** [comment]
watch me

**Comment by jemand771** [comment]
*resolved*

**Comment by jemand771** [comment]
jk

**Comment by DSczyrba** [comment]
Arbeitet
