### ISSUE TITLE
(nicht-) invertierender verstärker: verschiedene r_a

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#20]
r_a ist grundsätzlich der wechselstromausgangswiderstand. in 1.6.1.1/16.1.2 gibt's davon aber insgesamt 3 varianten: r_a, r_aL und r'_a.
vorschlag rausfinden und beschriften, evtl. vereinheitlichen, was dasvon was ist ist.
![image](https://user-images.githubusercontent.com/19669567/131879358-6f2c7060-104e-4325-8b5f-10e78b80fb72.png)

**Comment by jemand771** [comment]
die letzte zeile auf dem screenshot ist auch witzig, das impliziert dass V = V_0. ist glaube nicht so gedacht

**Comment by jemand771** [comment]
r_{GL} ist r-gleichtakt. frag mich nicht was das heisst
formel beim nichtinvertierenden sollte auch r'_a = r_a * V/V_o sein.
r'_a ist dabei der ausgangswiderstand (da wo Ua ist) der schaltung.
r_a ist der ausgangswiderstand des OPV (das scheint 'ne spec des bauteils zu sein)

**Comment by jemand771** [comment]
noch zu tun: was ist denn r_aL in der FS? wäre interessant zu wissen, wo das her kommt ^^
(und was das mit r_{GL} zu tun hat)

**Comment by TheColin21** [comment]
r_aL klingt für mich nach "mit Last"

**Comment by TheColin21** [comment]
> 
> 
> die letzte zeile auf dem screenshot ist auch witzig, das impliziert dass V = V_0. ist glaube nicht so gedacht

inwiefern tut es das?

**Comment by jemand771** [comment]
> inwiefern tut es das?

mit mathe:
wenn a = a * (b/c) kannst du beide seiten durch a teilen, d.h. a = b/c. dann noch *c und du hast b=c.

jedenfalls sollte das r'_a = r_a * ... sein, d.h. auf der linken seite der gleichung noch ein strich ran

**Comment by jemand771** [comment]
zu deinem r_aL: ja, mit last klingt interessant, aber der reinhold nennt das r_a_{GL} oder "r-gleichtakt" - was das mit r-last zu tun hat ist mir gerade noch nicht klar

das braucht man auch für eine von den aufgaben glaube ich

**Comment by TheColin21** [comment]
nennt er es wrkl r_a_{GL} oder r_a_{Gl} ? ich denke GL einfach für gleichtakt und mit r_L hat das nichts zu tun... aber nen R_L oderso gibts ja häufiger

**Comment by jemand771** [comment]
guck mal bitte ins reinhold-skript für nichtinvertierende verstärker. da steht glaube r_e = r_{GL} oder r_e = r_a_{GL} (gerade nicht mehr sicher)
jedenfalls, wenn das alles das gleiche ist, meint es sicher auch das gleiche

**Comment by TheColin21** [comment]
> 
> 
> > inwiefern tut es das?
> 
> mit mathe:
> wenn a = a * (b/c) kannst du beide seiten durch a teilen, d.h. a = b/c. dann noch *c und du hast b=c.
> 
> jedenfalls sollte das r'_a = r_a * ... sein, d.h. auf der linken seite der gleichung noch ein strich ran

fuck stimmt

**Comment by TheColin21** [comment]
> 
> 
> guck mal bitte ins reinhold-skript für nichtinvertierende verstärker. da steht glaube r_e = r_{GL} oder r_e = r_a_{GL} (gerade nicht mehr sicher)
> jedenfalls, wenn das alles das gleiche ist, meint es sicher auch das gleiche

steht da tatsächlich, GL... so n mist

**Comment by TheColin21** [comment]
https://www.elektronik-kompendium.de/sites/slt/0210151.htm die sagen r_a ~ 0... 
würde ich wahrscheinlich so übernehmen, klingt sinnvoll. die aktuelle formel bringt ja nichts

**Comment by jemand771** [comment]
aka "niederohmig" - das hab schonmal gehört irgendwo

ich glaub das einfach so fest zu definieren ist auch nicht so das wahre. naja, was will man machen ^^

**Comment by TheColin21** [comment]
bessere idee? xD sonst mach ichs so. oder wir haun die ganz raus

**Comment by jemand771** [comment]
wie bei den meissten sachen hier: mir egal, weil jetzt hab ich's einmal im kopf xD
spricht was dagegen, einfach alles rein zu schmeissen und ne notiz like "ich weiss doch auch nicht" ? xD
also r_e = r_{GL} = r_aL wiggly= 0\Omaga

**Comment by TheColin21** [comment]
auch ne Idee. dann mach ich das so (auch in ner PR, die nachricht kann man sicherlich falsch verstehen xD)
