### ISSUE TITLE
integrierverstärker

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#21]
![image](https://user-images.githubusercontent.com/19669567/131888930-3d3c4dad-78b5-4fd3-b248-6115f796d35f.png)
sorry wörter xd

**Comment by jemand771** [comment]
wörter: beim differenzierverstärker steht die formel mit du/dt da, da kann man noch drauf kommen dass man da auch einfach die deltas (differenzen der werte gegenüber anfangszustand und endzustand) einsetzen kann. beim integrierverstärker steht nur die formel mit integral, da ist das weniger offensichtlich. ich würde auf jeden fall beim integrierer die obere formel aus meinem screenshot ersetzen, beim differnzierer isses nicht so wichtig (screenshot differenzierer aus skript unten)
![image](https://user-images.githubusercontent.com/19669567/131896007-7f25bdfe-8267-434e-b746-bde1945a6011.png)

**Comment by TheColin21** [comment]
ich würde beide ergänzen. also die erste aus dem ersten bild bei integerer, die zweite aus dem zweiten bei differenzierer (mit an die -Ua formel dran) korrekt?

abgesehen davon: -Ua oder -ua ? is das bei Integrierer bei deinem Bild mit absicht klein? dann sollten wir es anpassen

**Comment by jemand771** [comment]
ich sag mal so: ob das gross oder klein ist ist grundsätzlich egal, weil ja weder weiss was gemeint ist
aber: das macht so schon richtig sinn:
* der integrierer leitet auf (pain), d.h. er macht z.b. aus einer konstanten spannung einen veränderlichen verlauf. deshalb heisst es dort Ue und ua
* der differenzierer leitet ab, d.h. der macht z.b. aus einer geraden eine konstante -> aus veränderlicher grösse (man könnte sagen wechselstrom) wird eine konstante. daher sind es dort Ua und ue
* das alles auf der basis, dass man U für gleichspannung und u für wechselpannung nimmt (siehe liebild :b)

**Comment by jemand771** [comment]
noch als erklärung zum zusammenhang:
* in bild 1 wurden einfach nur beide seiten der formel intigriert und der faktor 1/(RC) vor gezogen
* in bild 2 wird gezeigt, dass man statt das "wirklich" zu differenzieren (also mint infinitesimal kleinem intervall) auch einfach zwei echte intervalle einsetzen kann
* ---> die 4. schaltung auf dieser seite (github issue) ergibt sich von selbst, die 1. eventuell nicht. aus der 1. ergibt sich dann ein analog mit deltas statt d's wie von 3 zu 4

**Comment by TheColin21** [comment]
okay, also so ergänzen wie ich oben geschrieben hab oder anders?

**Comment by jemand771** [comment]
kannst du so machen, ja. beim differenzierer braucht man eigentlich keine 2 schaltungen, ist aber egal ^^

**Comment by TheColin21** [comment]
keine 2 Formeln meinste? wie gesagt, ich hänge das einfach an die bestehende, dazu mach ich wahrscheinlich ne PR

**Comment by jemand771** [comment]
versteh gerade nicht was du mit "ranhängen" meinst aber mach mal
tldr: beim integrierer find ich die 2. wichtig, beim differenzierer reicht es so wie's gerade ist. mehr ist optional
