### ISSUE TITLE
PN-übergang

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#23]
wollen wir was in der art übernehmen? ist denke nicht sehr wichtig (theorie fragt er sicher nicht), gehört aber so somewhat dazu
![image](https://user-images.githubusercontent.com/19669567/131900890-ee988767-4554-48b5-9164-6b2445504b06.png)

**Comment by TheColin21** [comment]
ist ne idee, würde ich in SVG machen

**Comment by TheColin21** [comment]
weigert sich grade bei mir, hab den branch mal hochgeladen, baut aber nicht. auf weirde weise

**Comment by jemand771** [comment]
hm, echt komisch. liegt aber auf jeden fall an der svg selbst, da kenn ich mich zu wenig aus :c

**Comment by TheColin21** [comment]
ich kapier einfach nicht, was da kaputt geht xD

**Comment by TheColin21** [comment]
weigert sich, nicht wichtig genug, zu viel Arbeit --> ignore
