### ISSUE TITLE
mehr m2u (?)

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#24]
übernehmen oder nicht? weiss noch nicht was das uns überhaupt sagen will, formeln dazu gibt's auch nicht
![image](https://user-images.githubusercontent.com/19669567/131902922-ca56f78c-0268-4b07-8451-b3233fbfb93a.png)

**Comment by TheColin21** [comment]
das würde ich wahrscheinlich weglassen
