### ISSUE TITLE
Bild LC-sieb ist falsch

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#25]
aktuelles bild:
![image](https://user-images.githubusercontent.com/19669567/131903196-bf79283f-4da3-4a57-a699-be973bd48876.png)

bild kevin:
![image](https://user-images.githubusercontent.com/19669567/131903177-8d12275a-2138-43b9-9ad7-aa47dfb1cf8c.png)

da fehlt einfach mal ganz frech der C_L.
R_L und dier gleichrichter oben links sind optional denke ich

**Comment by TheColin21** [comment]
![Siebung_LC](https://user-images.githubusercontent.com/24256864/131963955-9e619e8c-9aec-4f33-a2f6-f78bcd3ae6eb.GIF)
das ist die originale "Siebung_LC" aus der Cloud. Keine Ahnung was da jetzt wie korrekt ist

**Comment by jemand771** [comment]
kannst du nochmal in kevin's FS gucken, ob er ne formel für C_L hat? falls nicht lassen wir unsers einfach so, man muss da sicher eh nix dran rechnen

**Comment by TheColin21** [comment]
hat keine, lassen wir so
