### ISSUE TITLE
Lineare spannungsregler

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#26]
yoink?
![image](https://user-images.githubusercontent.com/19669567/131903376-963f2a1c-b779-4b87-a414-ad830485048f.png)

**Comment by TheColin21** [comment]
yoink. wo hin?

**Comment by jemand771** [comment]
ist ein eigens kapitel. mir egal wohin
irgendwo zwischen Br ¨uckengleichrichter = ”
Gratzbr ¨ucke“ und Diode als Schalter?

idee dahinter: für den spannungsregler braucht man erstmal gleichstrom ^^

**Comment by jemand771** [comment]
schön, dass umlaute aus latex pdfs kopieren immernoch kaput ist xD

**Comment by TheColin21** [comment]
okay, mache ich

**Comment by TheColin21** [comment]
> 
> 
> schön, dass umlaute aus latex pdfs kopieren immernoch kaput ist xD

grade gefixt

**Comment by TheColin21** [comment]
![grafik](https://user-images.githubusercontent.com/24256864/131981962-aa2baf6c-1c29-43f9-a553-31f41238c8c8.png)
was ist dies @jemand771  ?
