### ISSUE TITLE
andere typen von dioden

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#28]
![image](https://user-images.githubusercontent.com/19669567/131904151-1b5a5fcb-2bc9-4c86-b202-2d74bad736a8.png)

**Comment by jemand771** [comment]
edit: kapazitätsdiode ist teilw. drin

**Comment by TheColin21** [comment]
also 13 zu Dioden umbennen, 13.1 kapazitätsdioden mit aktuellem Inhalt
13.2 Tunneldiode mit Schaltzeichen
13.3 Schottky mit Schaltzeichen
oder gehören die Formeln alle zu Dioden allgemein? dann natürlich die quasi in 13.0... und wahlweise keine Unterkapitel sondern zB itemize

**Comment by jemand771** [comment]
/shrug :D
ich guck abends nochmal in meinem zeug nach

**Comment by jemand771** [comment]
witzigerweise hab ich die ganzen formeln die in der FS zu z-dioden stehen gar nicht, da fehlt wahrscheinlich eine seite oder so.

zu den anderen dioden-arten (kapazität, tunnel, schottky) hab ich zwar paar skizzen und stichpunkte zur funktionsweise, aber keine wirklichen formeln. das ist wahrscheinlich nur zur allgemeinen info dran gewesen, nicht zum rechnen

**Comment by jemand771** [comment]
ob wir jetzt "fyi" die schlatzeichen und namen der anderen dioden mit reinschreiben oder das einfach so lassen wie bis jetzt ist mir von daher egal :D

**Comment by TheColin21** [comment]
in dem Fall würde ich das so lassen
