### ISSUE TITLE
grenzwerte bpt

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#29]
![image](https://user-images.githubusercontent.com/19669567/131904438-0ceb09a1-e902-44e1-a903-3ec9bd4b28ec.png)

**Comment by jemand771** [comment]
dazu noch: verlustleistung P_V (denke ich jedenfalls dass es das heisst)
![image](https://user-images.githubusercontent.com/19669567/131904551-2fd2d336-f593-4dbc-9f82-f08e054aa002.png)

**Comment by TheColin21** [comment]
wo genau würdest du das hin setzen?

**Comment by jemand771** [comment]
mit zu den bpt. evtl. sogar als erstes unterkapitel

**Comment by TheColin21** [comment]
okay, haste bock? xD

**Comment by jemand771** [comment]
nö :)

**Comment by TheColin21** [comment]
...

**Comment by TheColin21** [comment]
> 
> 
> dazu noch: verlustleistung P_V (denke ich jedenfalls dass es das heisst)
> ![image](https://user-images.githubusercontent.com/19669567/131904551-2fd2d336-f593-4dbc-9f82-f08e054aa002.png)

bereits drin

**Comment by TheColin21** [comment]
@jemand771  hat sich doch noch freiwillig gemeldet

**Comment by TheColin21** [comment]
![image](https://user-images.githubusercontent.com/24256864/132088076-6bcaafb2-a924-421f-a5ac-f9028b0390e3.png)

so in Kevins Aufzeichnungen, klingt etwas sinnvoller?

**Comment by jemand771** [comment]
das sagt ja grundsätzlich das gleiche aus, ich versteh aber nicht was xD

**Comment by TheColin21** [comment]
weglassen? bringt nicht wirklich was zum Rechnen würde ich sagen.
