### ISSUE TITLE
thermische ap-stabilisierung durch thermistor

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#30]
![image](https://user-images.githubusercontent.com/19669567/131904645-d5128fef-caaa-41d9-b2a2-9ee09fbd9387.png)

**Comment by TheColin21** [comment]
was genau davon soll wo hin?

**Comment by jemand771** [comment]
thermische ap-stabilisierung durch thermistor, im gegensatz zur thermischen ap-stabilisierung durch die anderen beiden verfahren. d.h. das kommt mit zur thermischen ap-stabilisierung in der FS.
ich würde das bild übernehmen und evtl. die erklärung oben, das das bringt

**Comment by TheColin21** [comment]
okay, mach ich
