### ISSUE TITLE
kevin's FS vergleichen: FET und OPV

### ISSUE THREAD

**Issue by jemand771** [TheColin21/Formelsammlung-EB-Latex#32]
so weit bin ich nicht mehr gekommen :D
opv sieht denke schon echt gut aus, von fet hab ich null plan und kann schlecht einschätzen, was fehlt

**Comment by jemand771** [comment]
ach so xD

**Comment by jemand771** [comment]
bis auf das hier bei FET (vor den beispiel-schaltungen) ist unsers komplett
![image](https://user-images.githubusercontent.com/19669567/132128231-f1729631-df24-46be-bb8d-c9e76516d3eb.png)

**Comment by TheColin21** [comment]
so ziemlich alles hier ist vorhanden, aber etwas anders angeordnet. Die Schaltungen sind nicht in der Form vorhanden, dafür andere
